
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue May 14 16:14:30 CEST 2002
//----------------------------------------------------

package elias.agent.authoring.patterncompiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NAMED = 12;
  public static final int AND = 4;
  public static final int REPEAT = 11;
  public static final int OPTLBRACK = 9;
  public static final int EOF = 0;
  public static final int BEFORE = 2;
  public static final int PREDEFINED_PATTERN = 13;
  public static final int RBRACK = 6;
  public static final int TERMINAL = 14;
  public static final int error = 1;
  public static final int LBRACK = 7;
  public static final int NOT = 5;
  public static final int SEARCH = 10;
  public static final int OR = 3;
  public static final int OPTRBRACK = 8;
}

